--ODEV8--

--1
create table employee (id integer, name varchar(50), birthday date, email varchar(100));
--2
insert into employee (id, name, birthday , email) values (1, 'Sherri', '1934-02-24', 'skingswood0@stumbleupon.com');
insert into employee (id, name, birthday , email) values (2, 'Wallis', '2003-01-03', 'wdrummond1@ocn.ne.jp');
insert into employee (id, name, birthday , email) values (3, 'Bird', '1942-06-24', 'bsommerscales2@census.gov');
insert into employee (id, name, birthday , email) values (4, 'Janeta', '1902-05-27', 'jminchinton3@vkontakte.ru');
insert into employee (id, name, birthday , email) values (5, 'Augusta', '1923-10-08', 'amarkovic4@friendfeed.com');
insert into employee (id, name, birthday , email) values (6, 'Blondy', '2014-09-18', 'btrippett5@sciencedirect.com');
insert into employee (id, name, birthday , email) values (7, 'Gilbert', null, 'glinbohm6@privacy.gov.au');
insert into employee (id, name, birthday , email) values (8, 'Selina', '1934-02-17', 'sshowering7@nationalgeographic.com');
insert into employee (id, name, birthday , email) values (9, 'Kayle', '1936-12-13', 'kphelipeau8@wikispaces.com');
insert into employee (id, name, birthday , email) values (10, 'Ronni', '2010-02-17', 'rsooper9@slate.com');
insert into employee (id, name, birthday , email) values (11, 'Davide', '1900-08-12', null);
insert into employee (id, name, birthday , email) values (12, 'Gian', '1969-04-21', 'ggollyb@scientificamerican.com');
insert into employee (id, name, birthday , email) values (13, 'Ferd', '2019-07-22', 'fconditc@economist.com');
insert into employee (id, name, birthday , email) values (14, 'Yehudi', null, 'ycardusd@webs.com');
insert into employee (id, name, birthday , email) values (15, 'Godiva', '2005-04-28', 'gpeacope@alexa.com');
insert into employee (id, name, birthday , email) values (16, 'Georgette', '2006-10-04', 'gbrunskillf@privacy.gov.au');
insert into employee (id, name, birthday , email) values (17, 'Heriberto', null, 'hmacginlayg@webmd.com');
insert into employee (id, name, birthday , email) values (18, 'Harrie', '1973-01-19', null);
insert into employee (id, name, birthday , email) values (19, 'Maude', '1902-08-08', 'mbasketfieldi@tmall.com');
insert into employee (id, name, birthday , email) values (20, 'Ninetta', '2017-11-05', 'nsellwoodj@weibo.com');
insert into employee (id, name, birthday , email) values (21, 'Hertha', '1916-05-12', 'hbainbriggek@xinhuanet.com');
insert into employee (id, name, birthday , email) values (22, 'Rachele', '1956-10-12', 'rbachsl@edublogs.org');
insert into employee (id, name, birthday , email) values (23, 'Shelia', null, 'stettersellm@alibaba.com');
insert into employee (id, name, birthday , email) values (24, 'Darcee', '1917-03-02', 'dswantonn@php.net');
insert into employee (id, name, birthday , email) values (25, 'Darin', '1963-11-06', 'dpuxleyo@bloomberg.com');
insert into employee (id, name, birthday , email) values (26, 'Karisa', '2001-08-26', 'krucklessep@naver.com');
insert into employee (id, name, birthday , email) values (27, 'Spencer', '1930-11-06', 'swhyffenq@prlog.org');
insert into employee (id, name, birthday , email) values (28, 'Jerrilee', null, 'jhogbourner@sciencedirect.com');
insert into employee (id, name, birthday , email) values (29, 'Micky', null, null);
insert into employee (id, name, birthday , email) values (30, 'Hendrika', '1965-03-29', 'hchrishopt@shareasale.com');
insert into employee (id, name, birthday , email) values (31, 'Julianna', '1947-05-06', 'jbenbricku@irs.gov');
insert into employee (id, name, birthday , email) values (32, 'Yehudit', '2014-06-03', 'ymoscov@wufoo.com');
insert into employee (id, name, birthday , email) values (33, 'Roobbie', null, 'rnockallsw@dailymotion.com');
insert into employee (id, name, birthday , email) values (34, 'Audrey', '1920-08-03', 'apevsnerx@vkontakte.ru');
insert into employee (id, name, birthday , email) values (35, 'Calv', '1946-02-11', 'caggety@so-net.ne.jp');
insert into employee (id, name, birthday , email) values (36, 'Zitella', '1964-02-12', 'zkynochz@apache.org');
insert into employee (id, name, birthday , email) values (37, 'Pebrook', '1907-05-09', 'padolphine10@infoseek.co.jp');
insert into employee (id, name, birthday , email) values (38, 'Ethe', '1937-03-06', 'emelmar11@netlog.com');
insert into employee (id, name, birthday , email) values (39, 'Doretta', '1932-06-25', 'dalmack12@earthlink.net');
insert into employee (id, name, birthday , email) values (40, 'Marrilee', '1903-03-27', null);
insert into employee (id, name, birthday , email) values (41, 'Chiarra', null, 'csieghart14@wikispaces.com');
insert into employee (id, name, birthday , email) values (42, 'Rabi', '2002-03-14', 'rbosch15@sciencedaily.com');
insert into employee (id, name, birthday , email) values (43, 'Electra', '1986-09-22', 'emantz16@freewebs.com');
insert into employee (id, name, birthday , email) values (44, 'Laurens', '1945-06-14', 'lajsik17@yellowbook.com');
insert into employee (id, name, birthday , email) values (45, 'Alverta', '1945-07-01', 'akimm18@godaddy.com');
insert into employee (id, name, birthday , email) values (46, 'Wylma', null, 'wpringley19@live.com');
insert into employee (id, name, birthday , email) values (47, 'Rand', '1970-09-12', 'rdelgadillo1a@statcounter.com');
insert into employee (id, name, birthday , email) values (48, 'Sutherlan', '1926-03-17', 'spomfrey1b@soundcloud.com');
insert into employee (id, name, birthday , email) values (49, 'Othella', '1959-12-05', 'osmallacombe1c@wikimedia.org');
insert into employee (id, name, birthday , email) values (50, 'Ollie', '1929-12-16', 'ogergolet1d@indiatimes.com');
insert into employee (id, name, birthday , email) values (51, 'Harley', '1999-11-05', 'hguerrin1e@washingtonpost.com');
insert into employee (id, name, birthday , email) values (52, 'Saleem', '1999-10-24', null);
insert into employee (id, name, birthday , email) values (53, 'Koenraad', '1966-11-13', 'ktargetter1g@dedecms.com');
insert into employee (id, name, birthday , email) values (54, 'Allyson', null, 'apurdon1h@washingtonpost.com');
insert into employee (id, name, birthday , email) values (55, 'Chadwick', '1948-02-10', 'ccharrett1i@google.com.hk');
insert into employee (id, name, birthday , email) values (56, 'Vite', '1990-08-08', 'vlangton1j@flickr.com');
insert into employee (id, name, birthday , email) values (57, 'Cherish', '2014-01-17', 'cklimowski1k@harvard.edu');
insert into employee (id, name, birthday , email) values (58, 'Erick', null, 'erennix1l@sogou.com');
insert into employee (id, name, birthday , email) values (59, 'Bonita', '1993-07-31', 'bkobel1m@virginia.edu');
insert into employee (id, name, birthday , email) values (60, 'Minnaminnie', '2004-01-14', 'mbruhnsen1n@dedecms.com');
insert into employee (id, name, birthday , email) values (61, 'Aridatha', '1904-11-03', 'avye1o@sakura.ne.jp');
insert into employee (id, name, birthday , email) values (62, 'Nanci', '2005-04-06', 'nandrzejowski1p@stanford.edu');
insert into employee (id, name, birthday , email) values (63, 'Breena', '2017-08-08', 'bdy1q@ifeng.com');
insert into employee (id, name, birthday , email) values (64, 'Brinna', '1977-10-02', 'balves1r@icio.us');
insert into employee (id, name, birthday , email) values (65, 'Kev', null, null);
insert into employee (id, name, birthday , email) values (66, 'Allister', '2020-07-16', 'asheppard1t@kickstarter.com');
insert into employee (id, name, birthday , email) values (67, 'Hi', '1906-04-30', 'hbock1u@slideshare.net');
insert into employee (id, name, birthday , email) values (68, 'Dennison', '1919-04-09', 'dcausnett1v@foxnews.com');
insert into employee (id, name, birthday , email) values (69, 'Ed', '1935-01-20', 'ebargh1w@hubpages.com');
insert into employee (id, name, birthday , email) values (70, 'Dur', '1917-09-30', 'dgatrell1x@trellian.com');
insert into employee (id, name, birthday , email) values (71, 'Trixie', null, 'tblunsden1y@china.com.cn');
insert into employee (id, name, birthday , email) values (72, 'Korella', '2012-06-15', 'kbroadhead1z@360.cn');
insert into employee (id, name, birthday , email) values (73, 'Jareb', '1965-03-27', 'jvernall20@fc2.com');
insert into employee (id, name, birthday , email) values (74, 'Claudio', null, null);
insert into employee (id, name, birthday , email) values (75, 'Annadiana', '1939-01-04', 'avial22@timesonline.co.uk');
insert into employee (id, name, birthday , email) values (76, 'Lucas', '1917-11-18', null);
insert into employee (id, name, birthday , email) values (77, 'Brana', null, 'bducham24@about.com');
insert into employee (id, name, birthday , email) values (78, 'Holli', null, 'hlendrem25@bigcartel.com');
insert into employee (id, name, birthday , email) values (79, 'Roger', '1984-01-27', 'rarkley26@accuweather.com');
insert into employee (id, name, birthday , email) values (80, 'Glenden', null, 'ggruszka27@google.co.jp');
insert into employee (id, name, birthday , email) values (81, 'Miguel', '1919-09-27', 'mwalley28@godaddy.com');
insert into employee (id, name, birthday , email) values (82, 'Stuart', '1927-04-22', 'sabbotts29@imgur.com');
insert into employee (id, name, birthday , email) values (83, 'Darby', '1923-12-10', null);
insert into employee (id, name, birthday , email) values (84, 'Allie', '1968-01-28', null);
insert into employee (id, name, birthday , email) values (85, 'Rudolph', '1929-06-25', null);
insert into employee (id, name, birthday , email) values (86, 'Kit', '1955-05-31', 'khewes2d@facebook.com');
insert into employee (id, name, birthday , email) values (87, 'Geneva', '2020-01-20', 'glead2e@un.org');
insert into employee (id, name, birthday , email) values (88, 'Madlen', null, 'mbagster2f@army.mil');
insert into employee (id, name, birthday , email) values (89, 'Jillie', '1916-05-09', 'jvallens2g@jugem.jp');
insert into employee (id, name, birthday , email) values (90, 'Broddie', null, 'bduddy2h@163.com');
insert into employee (id, name, birthday , email) values (91, 'Joan', '1935-02-14', 'jbaylay2i@sphinn.com');
insert into employee (id, name, birthday , email) values (92, 'Toinette', '1928-10-27', 'tdaniels2j@odnoklassniki.ru');
insert into employee (id, name, birthday , email) values (93, 'Giustina', '1930-06-04', 'gnaismith2k@amazon.com');
insert into employee (id, name, birthday , email) values (94, 'Edee', '1939-03-26', 'eschutte2l@jiathis.com');
insert into employee (id, name, birthday , email) values (95, 'Randi', null, 'rmathissen2m@photobucket.com');
insert into employee (id, name, birthday , email) values (96, 'Ferdinanda', '1935-04-05', 'fyushachkov2n@wunderground.com');
insert into employee (id, name, birthday , email) values (97, 'Dollie', '1989-04-19', 'ddemorena2o@123-reg.co.uk');
insert into employee (id, name, birthday , email) values (98, 'Si', '1916-10-10', null);
insert into employee (id, name, birthday , email) values (99, 'Rustin', null, 'rfotitt2q@plala.or.jp');
insert into employee (id, name, birthday , email) values (100, 'Giacomo', null, 'gwasielewski2r@tumblr.com');
--3
update employee set name='Seher',birthday='11/03/1997', email='s@gmail.com' where id=50;
update employee set name ='Erhan',email='e@gmail.com' where name='Giustina';
update employee set birthday='10/02/2020' where id=45;
update employee set email='d@gmail.com' where name like '%n';
update employee set name='Ada' where email like 'r%';
--4
delete from employee where id=50;
delete from employee where name='Erhan';
delete from employee where email='d@gmail.com';
delete from employee where birthday='10/02/2020';